### ISSUE TITLE
Missing curriculum content: Theory and Theorizing in the Social Sciences (Tom Davidson)

### ISSUE THREAD

**Issue by joan-wang** [dssg/hitchhikers-guide#104]
Need content for Ongoing Curriculum: Theory and Theorizing in the Social Sciences (Tom Davidson)

**Comment by t-davidson** [comment]
I think that the slides got deleted when UChicago removed our Google Drive access. Jane asked me about it last year and I couldn't find it anywhere. I'll have another look to see if I can track down the slides anywhere.

**Comment by t-davidson** [comment]
Here is the link but no file: https://docs.google.com/a/cornell.edu/presentation/d/16j5yeix7cc2Cv_joDX6KOHMx1kiR5lYkVu4O2l8TiiU/edit?usp=sharing_eid&ts=57999141
